services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  fastapi:
    image: ghcr.io/dominik-farlik/nchls-backend:latest
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./data/uploads:/app/uploads

  nginx:
    image: ghcr.io/dominik-farlik/nchls-frontend:latest
    restart: always
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt:ro
      - ./letsencrypt/lib:/var/lib/letsencrypt
      - ./letsencrypt/webroot:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/lib:/var/lib/letsencrypt
      - ./letsencrypt/webroot:/var/www/certbot

volumes:
  mongo_data:
    external: true
    name: nchls_mongo_data